
#Config to adjust world settings
[World]
	#Gives the ap documentation to new players on a world.
	givePlayerBookOnJoin = true
	#Enable the villager structures for the computer scientist.
	enableVillagerStructures = true
	#The weight of the villager structures
	#Range: 0 ~ 16000
	villagerStructureWeight = 10

